### ISSUE TITLE
transformClassesWithTraceManTransformForDebug

### ISSUE THREAD

**Issue by 103style** [zhengcx/MethodTraceMan#18]
AndroidStudio 3.5.2
```
java.lang.NullPointerException
	at org.objectweb.asm.Item.set(Item.java:233)
	at org.objectweb.asm.ClassWriter.newMethodItem(ClassWriter.java:1498)
	at org.objectweb.asm.MethodWriter.visitMethodInsn(MethodWriter.java:899)
	at cn.cxzheng.tracemanplugin.TraceMethodVisitor.onMethodEnter(TraceMethodVisitor.kt:36)
	at org.objectweb.asm.commons.AdviceAdapter.visitCode(AdviceAdapter.java:112)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1125)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at org.objectweb.asm.ClassReader$accept.call(Unknown Source)
	at cn.cxzheng.tracemanplugin.TraceManTransform$_traceSrcFiles_closure2.doCall(TraceManTransform
```

### update
**2019/11/28  16:33**
同步最新代码之后，没有出现这个问题了 。 
#25  但是目前存在这个问题

**Comment by githulining** [comment]
i got the reason,i put the file in the wrong place      tranceconfig.txt

**Comment by ihrthk** [comment]
Caused by: java.lang.NullPointerException
        at org.objectweb.asm.Item.set(Item.java:233)
        at org.objectweb.asm.ClassWriter.newMethodItem(ClassWriter.java:1498)
        at org.objectweb.asm.MethodWriter.visitMethodInsn(MethodWriter.java:899)
        at cn.cxzheng.tracemanplugin.TraceMethodVisitor.onMethodEnter(TraceMethodVisitor.kt:36)
        at org.objectweb.asm.commons.AdviceAdapter.visitCode(AdviceAdapter.java:112)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1125)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
        at org.objectweb.asm.ClassReader$accept$2.call(Unknown Source)
        at cn.cxzheng.tracemanplugin.TraceManTransform$_traceSrcFiles_closure2.doCall(TraceManTransform.groovy:114)
        at cn.cxzheng.tracemanplugin.TraceManTransform.traceSrcFiles(TraceManTransform.groovy:108)
        at cn.cxzheng.tracemanplugin.TraceManTransform$traceSrcFiles.callStatic(Unknown Source)
        at cn.cxzheng.tracemanplugin.TraceManTransform$_transform_closure1$_closure3.doCall(TraceManTransform.groovy:67)
        at cn.cxzheng.tracemanplugin.TraceManTransform$_transform_closure1.doCall(TraceManTransform.groovy:66)
        at cn.cxzheng.tracemanplugin.TraceManTransform.transform(TraceManTransform.groovy:65)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more



同样的问题

**Comment by newcman** [comment]
同样的问题，大佬怎么解～
Caused by: java.lang.NullPointerException
        at org.objectweb.asm.Item.set(Item.java:233)
        at org.objectweb.asm.ClassWriter.newMethodItem(ClassWriter.java:1498)
        at org.objectweb.asm.MethodWriter.visitMethodInsn(MethodWriter.java:899)
        at cn.cxzheng.tracemanplugin.TraceMethodVisitor.onMethodEnter(TraceMethodVisitor.kt:36)
        at org.objectweb.asm.commons.AdviceAdapter.visitCode(AdviceAdapter.java:112)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1125)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
        at org.objectweb.asm.ClassReader$accept.call(Unknown Source)
        at cn.cxzheng.tracemanplugin.TraceManTransform.traceJarFiles(Trac


apply plugin: "cn.cxzheng.asmtraceman"
traceMan {
    open = true //这里如果设置为false,则会关闭插桩
    logTraceInfo = false //这里设置为true时可以在log日志里看到所有被插桩的类和方法
    traceConfigFile = "${project.projectDir}/traceconfig.txt"
}

**Comment by luckybilly** [comment]
应该是traceconfig.txt文件没找到，请确认一下文件路径是否正确（作者在issue #14 中回答了这个问题）

**Comment by 103style** [comment]
@luckybilly 
 `traceconfig.txt` 目录确认没问题
 直接clone工程在 AndroidStudio 3.5.2版本 也有问题。

isssue #14 中有报错信息  
```
at cn.cxzheng.tracemanplugin.Config.parseTraceConfigFile(Config.kt:107)
```

这个报错并没有

**Comment by luckybilly** [comment]
@103style 我在回复你之前也遇到同样的问题，报错信息与你贴的一样，搜索issue之后发现是我的`traceconfig.txt`文件目录放错了（我放到了工程根目录），将`${project.projectDir}/traceconfig.txt`改成`${rootProject.projectDir}/traceconfig.txt`就OK了。
仅供参考哈
