### ISSUE TITLE
出现GC，卡死。最新版本。求解决

### ISSUE THREAD

**Issue by AdaiAndy** [zhengcx/MethodTraceMan#28]
2019-12-05 15:47:48.513 26120-26130 E/System: java.lang.StackOverflowError: stack size 1037KB
        at java.lang.ThreadLocal$ThreadLocalMap.getEntry(ThreadLocal.java:378)
        at java.lang.ThreadLocal$ThreadLocalMap.-wrap0(ThreadLocal.java)
        at java.lang.ThreadLocal.get(ThreadLocal.java:146)
        at android.os.Looper.myLooper(Looper.java:185)
        at cn.cxzheng.tracemanui.TraceMan.isInMainThread(TraceMan.java:113)
        at cn.cxzheng.tracemanui.TraceMan.start(TraceMan.java:30)
        at cn.cxzheng.tracemanui.utils.LogUtil.detail(LogUtil.kt)
        at cn.cxzheng.tracemanui.TraceMan.end(TraceMan.java:37)
        at cn.cxzheng.tracemanui.MethodTraceServerManager.getLogLevel(MethodTraceServerManager.kt:41)
        at cn.cxzheng.tracemanui.utils.LogUtil$Companion.detail(LogUtil.kt:18)
        at cn.cxzheng.tracemanui.utils.LogUtil.detail(LogUtil.kt)
        at cn.cxzheng.tracemanui.TraceMan.end(TraceMan.java:37)
        at cn.cxzheng.tracemanui.MethodTraceServerManager.getLogLevel(MethodTraceServerManager.kt:41)
        at cn.cxzheng.tracemanui.utils.LogUtil$Companion.detail(LogUtil.kt:18)
        at cn.cxzheng.tracemanui.utils.LogUtil.detail(LogUtil.kt)
        at cn.cxzheng.tracemanui.TraceMan.end(TraceMan.java:37)
        at cn.cxzheng.tracemanui.MethodTraceServerManager.getLogLevel(MethodTraceServerManager.kt:41)
        at cn.cxzheng.tracemanui.utils.LogUtil$Companion.detail(LogUtil.kt:18)
        at cn.cxzheng.tracemanui.utils.LogUtil.detail(LogUtil.kt)
        at cn.cxzheng.tracemanui.TraceMan.end(TraceMan.java:37)
        at cn.cxzheng.tracemanui.MethodTraceServerManager.getLogLevel(MethodTraceServerManager.kt:41)
        at cn.cxzheng.tracemanui.utils.LogUtil$Companion.detail(LogUtil.kt:18)
        at cn.cxzheng.tracemanui.utils.LogUtil.detail(LogUtil.kt)
        at cn.cxzheng.tracemanui.TraceMan.end(TraceMan.java:37)
        at cn.cxzheng.tracemanui.MethodTraceServerManager.getLogLevel(MethodTraceServerManager.kt:41)
        at cn.cxzheng.tracemanui.utils.LogUtil$Companion.detail(LogUtil.kt:18)
        at cn.cxzheng.tracemanui.utils.LogUtil.detail(LogUtil.kt)
        at cn.cxzheng.tracemanui.TraceMan.end(TraceMan.java:37)
        at cn.cxzheng.tracemanui.MethodTraceServerManager.getLogLevel(MethodTraceServerManager.kt:41)
        at cn.cxzheng.tracemanui.utils.LogUtil$Companion.detail(LogUtil.kt:18)
        at cn.cxzheng.tracemanui.utils.LogUtil.detail(LogUtil.kt)
        at cn.cxzheng.tracemanui.TraceMan.end(TraceMan.java:37)
        at cn.cxzheng.tracemanui.MethodTraceServerManager.getLogLevel(MethodTraceServerManager.kt:41)
        at cn.cxzheng.tracemanui.utils.LogUtil$Companion.detail(LogUtil.kt:18)
        at cn.cxzheng.tracemanui.utils.LogUtil.detail(LogUtil.kt)
        at cn.cxzheng.tracemanui.TraceMan.end(TraceMan.java:37)
        at cn.cxzheng.tracemanui.MethodTraceServerManager.getLogLevel(MethodTraceServerManager.kt:41)
        at cn.cxzheng.tracemanui.utils.LogUtil$Companion.detail(LogUtil.kt:18)
        at cn.cxzheng.tracemanui.utils.LogUtil.detail(LogUtil.kt)
        at cn.cxzheng.tracemanui.TraceMan.end(TraceMan.java:37)
        at cn.cxzheng.tracemanui.MethodTraceServerManager.getLogLevel(MethodTraceServerManager.kt:41)
        at cn.cxzheng.tracemanui.utils.LogUtil$Companion.detail(LogUtil.kt:18)
        at cn.cxzheng.tracemanui.utils.LogUtil.detail(LogUtil.kt)
        at cn.cxzheng.tracemanui.TraceMan.end(TraceMan.java:37)
        at cn.cxzheng.tracemanui.MethodTraceServerManager.getLogLevel(MethodTraceServerManager.kt:41)
        at cn.cxzheng.tracemanui.utils.LogUtil$Companion.detail(LogUtil.kt:18)
        at cn.cxzheng.tracemanui.utils.LogUtil.detail(LogUtil.kt)
        at cn.cxzheng.tracemanui.TraceMan.end(TraceMan.java:37)
        at cn.cxzheng.tracemanui.MethodTraceServerManager.getLogLevel(MethodTraceServerManager.kt:41)
        at cn.cxzheng.tracemanui.utils.LogUtil$Companion.detail(LogUtil.kt:18)
        at cn.cxzheng.tracemanui.utils.LogUtil.detail(LogUtil.kt)
        at cn.cxzheng.tracemanui.TraceMan.end(TraceMan.java:37)
        at cn.cxzheng.tracemanui.MethodTraceServerManager.getLogLevel(MethodTraceServerManager.kt:41)
        at cn.cxzheng.tracemanui.utils.LogUtil$Companion.detail(LogUtil.kt:18)
        at cn.cxzheng.tracemanui.utils.LogUtil.detail(LogUtil.kt)
        at cn.cxzheng.tracemanui.TraceMan.end(TraceMan.java:37)
        at cn.cxzheng.tracemanui.MethodTraceServerManager.getLogLevel(MethodTraceServerManager.kt:41)
    	at cn.cxzheng.tracemanui.utils.LogUti

**Comment by zhengcx** [comment]
好的，近期看一下

**Comment by zhengcx** [comment]
最新版本（1.0.7）优化了内存占用问题，并且使用了无侵入性的初始化方案，可以看一下最新的集成文档，升级一下依赖的版本
