### ISSUE TITLE
Execution failed for task ':app:transformClassesWithTraceManTransformForDebug'.

### ISSUE THREAD

**Issue by prism42** [zhengcx/MethodTraceMan#43]
> Task :app:transformClassesWithTraceManTransformForDebug
[MethodTraceMan]: transform()
parseTraceConfigFile start!!!!!!!!!!!!
tracepackage:我的项目包名信息手动删掉了格式为com/xxxx/xxxx
beatclass:cn/cxzheng/tracemanui/TraceMan

> Task :app:transformClassesWithTraceManTransformForDebug FAILED
> Task :app:mergeDebugNativeLibs
> Task :app:mergeDebugJavaResource

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithTraceManTransformForDebug'.
> java.lang.RuntimeException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

不知道这是什么原因，在新建Hello Word项目中，同样的操作配置没有问题可以运行，可以确定我的配置是没有问题的，但是在我的项目中就是运行不起来，无解

**Comment by shisishishisi** [comment]
同样问题

**Comment by WXZNJS** [comment]
同样问题求解

**Comment by daixj** [comment]
同样的问题，提示this feature require asm6,求解

**Comment by mr-torto** [comment]
Execution failed for task ':methodtraceman:transformClassesWithTraceManTransformForDebug.
> This feature requires ASM6


同样问题，求解，是引用的ASM库版本不对的问题，大佬救一波

**Comment by gitjp123** [comment]
同样的问题，求解
`Execution failed for task ':app:transformClassesWithTraceManTransformForChinaDebug'.
> java.lang.RuntimeException (no error message)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithTraceManTransformForChinaDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:205)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:203)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at 
`
